# Generated by Django 3.2.13 on 2022-06-17 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_questions_name_of_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_imglogo', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('country', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('quesion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profileuser')),
            ],
        ),
    ]
