# Generated by Django 3.2.13 on 2022-06-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswered',
        ),
    ]
