# Generated by Django 3.2.13 on 2022-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choices',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name_of_question',
        ),
        migrations.AddField(
            model_name='question',
            name='questionText',
            field=models.CharField(default='what is your name', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.CharField(default='radio', max_length=200),
        ),
    ]
