# Generated by Django 3.2.13 on 2022-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='location',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
