# Generated by Django 3.2.13 on 2022-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220710_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
