# Generated by Django 3.2.13 on 2022-06-15 13:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_img',
            new_name='company_logo',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_bio',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
