# Generated by Django 3.2.13 on 2022-06-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='options',
        ),
    ]
