# Generated by Django 3.2.13 on 2022-07-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_survey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
