# Generated by Django 3.2.13 on 2022-07-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
