# Generated by Django 3.2.13 on 2022-06-15 13:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
