# Generated by Django 3.2.13 on 2022-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_surveyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
            ],
        ),
    ]
