# Generated by Django 3.2.13 on 2022-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='name_of_question',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
